# Generated by Django 2.2.9 on 2020-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questrion_text',
            new_name='question_text',
        ),
    ]
